/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufrn.GUI;

import br.ufrn.interfaces.ConcreteAtualizarInformacoes;
import br.ufrn.interfaces.AtualizarInformacoes;
import context.arch.discoverer.Discoverer;

/**
 *
 * @author Residentes
 */
public class Cidade extends javax.swing.JFrame {

    /**
     * Creates new form Cidade
     */
    AtualizarInformacoes atualizarInformacoes;
    public Cidade() {
    	
        atualizarInformacoes = new ConcreteAtualizarInformacoes();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jStemperaturaArea1 = new javax.swing.JSlider();
        jCincendioArea1 = new javax.swing.JCheckBox();
        jSArea1 = new javax.swing.JSlider();
        jTlixo1 = new javax.swing.JSlider();
        jPanel4 = new javax.swing.JPanel();
        jSarea3 = new javax.swing.JSlider();
        jCincendioArea3 = new javax.swing.JCheckBox();
        jStemperaturaArea3 = new javax.swing.JSlider();
        jTlixo3 = new javax.swing.JSlider();
        jPanel5 = new javax.swing.JPanel();
        jSarea2 = new javax.swing.JSlider();
        jCincendioArea2 = new javax.swing.JCheckBox();
        jStemperaturaArea2 = new javax.swing.JSlider();
        jTlixo2 = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CIDADE");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Area 1"));

        jStemperaturaArea1.setMinimum(-50);
        jStemperaturaArea1.setValue(0);
        jStemperaturaArea1.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura"));
        jStemperaturaArea1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jStemperaturaArea1StateChanged(evt);
            }
        });

        jCincendioArea1.setText("Incendio");
        jCincendioArea1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCincendioArea1StateChanged(evt);
            }
        });
        jCincendioArea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCincendioArea1ActionPerformed(evt);
            }
        });

        jSArea1.setMaximum(400);
        jSArea1.setValue(0);
        jSArea1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nivel de poluicao"));
        jSArea1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSArea1StateChanged(evt);
            }
        });

        jTlixo1.setMaximum(250);
        jTlixo1.setValue(0);
        jTlixo1.setBorder(javax.swing.BorderFactory.createTitledBorder("Volume de lixo"));
        jTlixo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTlixo1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTlixo1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jCincendioArea1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jStemperaturaArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(jSArea1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jTlixo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCincendioArea1)
                .addGap(18, 18, 18)
                .addComponent(jStemperaturaArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTlixo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Area 3"));

        jSarea3.setMaximum(400);
        jSarea3.setValue(0);
        jSarea3.setBorder(javax.swing.BorderFactory.createTitledBorder("Nivel de poluicao"));
        jSarea3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSarea3StateChanged(evt);
            }
        });

        jCincendioArea3.setText("Incendio");
        jCincendioArea3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCincendioArea3StateChanged(evt);
            }
        });
        jCincendioArea3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCincendioArea3ActionPerformed(evt);
            }
        });

        jStemperaturaArea3.setMinimum(-50);
        jStemperaturaArea3.setValue(0);
        jStemperaturaArea3.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura"));
        jStemperaturaArea3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jStemperaturaArea3StateChanged(evt);
            }
        });

        jTlixo3.setMaximum(250);
        jTlixo3.setValue(0);
        jTlixo3.setBorder(javax.swing.BorderFactory.createTitledBorder("Volume de lixo"));
        jTlixo3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTlixo3StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCincendioArea3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSarea3, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(jStemperaturaArea3, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jTlixo3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSarea3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jCincendioArea3)
                .addGap(18, 18, 18)
                .addComponent(jStemperaturaArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTlixo3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Area 2"));

        jSarea2.setMaximum(400);
        jSarea2.setValue(0);
        jSarea2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nivel de poluicao"));
        jSarea2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSarea2StateChanged(evt);
            }
        });

        jCincendioArea2.setText("Incendio");
        jCincendioArea2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCincendioArea2StateChanged(evt);
            }
        });
        jCincendioArea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCincendioArea2ActionPerformed(evt);
            }
        });

        jStemperaturaArea2.setMinimum(-50);
        jStemperaturaArea2.setValue(0);
        jStemperaturaArea2.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperatura"));
        jStemperaturaArea2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jStemperaturaArea2StateChanged(evt);
            }
        });

        jTlixo2.setMaximum(250);
        jTlixo2.setValue(0);
        jTlixo2.setBorder(javax.swing.BorderFactory.createTitledBorder("Volume de lixo"));
        jTlixo2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTlixo2StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jCincendioArea2)
                        .addGap(0, 138, Short.MAX_VALUE))
                    .addComponent(jSarea2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jStemperaturaArea2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTlixo2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSarea2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCincendioArea2)
                .addGap(18, 18, 18)
                .addComponent(jStemperaturaArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jTlixo2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel2, jPanel4, jPanel5});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jStemperaturaArea1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jStemperaturaArea1StateChanged
       atualizarInformacoes.atualizarTemperatura(jStemperaturaArea1.getValue(), "area:1");
    }//GEN-LAST:event_jStemperaturaArea1StateChanged

    private void jSarea2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSarea2StateChanged
    	atualizarInformacoes.atualizarInformacoesPoluicao(jSarea2.getValue(), "area-2");
    }//GEN-LAST:event_jSarea2StateChanged

   
    private void jCincendioArea1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCincendioArea1StateChanged
    }//GEN-LAST:event_jCincendioArea1StateChanged

    private void jCincendioArea2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCincendioArea2StateChanged
      
    }//GEN-LAST:event_jCincendioArea2StateChanged

    private void jCincendioArea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCincendioArea1ActionPerformed
        atualizarInformacoes.atulaizarInformacoesIncendio(jCincendioArea1.isSelected(),"area-1");
    }//GEN-LAST:event_jCincendioArea1ActionPerformed

    private void jCincendioArea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCincendioArea2ActionPerformed
        atualizarInformacoes.atulaizarInformacoesIncendio(jCincendioArea2.isSelected(),"area-2");
    }//GEN-LAST:event_jCincendioArea2ActionPerformed

    private void jSArea1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSArea1StateChanged
        atualizarInformacoes.atualizarInformacoesPoluicao(jSArea1.getValue(), "area-1");
    }//GEN-LAST:event_jSArea1StateChanged

    private void jStemperaturaArea2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jStemperaturaArea2StateChanged
        atualizarInformacoes.atualizarTemperatura(jStemperaturaArea2.getValue(), "area:2");
    }//GEN-LAST:event_jStemperaturaArea2StateChanged

    private void jStemperaturaArea3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jStemperaturaArea3StateChanged
        atualizarInformacoes.atualizarTemperatura(jStemperaturaArea3.getValue(), "area:3");
    }//GEN-LAST:event_jStemperaturaArea3StateChanged

    private void jCincendioArea3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCincendioArea3ActionPerformed
        atualizarInformacoes.atulaizarInformacoesIncendio(jCincendioArea3.isSelected(),"area-3");
    }//GEN-LAST:event_jCincendioArea3ActionPerformed

    private void jCincendioArea3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCincendioArea3StateChanged

    }//GEN-LAST:event_jCincendioArea3StateChanged

    private void jSarea3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSarea3StateChanged
        atualizarInformacoes.atualizarInformacoesPoluicao(jSarea3.getValue(), "area-3");
    }//GEN-LAST:event_jSarea3StateChanged

    private void jTlixo1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jT1StateChanged
        atualizarInformacoes.atualizarInformacoesLixeira(jTlixo1.getValue(), "area-1");
    }//GEN-LAST:event_jT1StateChanged

    private void jTlixo2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jT2StateChanged
       atualizarInformacoes.atualizarInformacoesLixeira(jTlixo2.getValue(), "area-2");
    }//GEN-LAST:event_jTlixo2StateChanged

    private void jTlixo3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTlixo3StateChanged
        atualizarInformacoes.atualizarInformacoesLixeira(jTlixo3.getValue(), "area-3");
    }//GEN-LAST:event_jTlixo3StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cidade().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCincendioArea1;
    private javax.swing.JCheckBox jCincendioArea2;
    private javax.swing.JCheckBox jCincendioArea3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSlider jSArea1;
    private javax.swing.JSlider jSarea2;
    private javax.swing.JSlider jSarea3;
    private javax.swing.JSlider jStemperaturaArea1;
    private javax.swing.JSlider jStemperaturaArea2;
    private javax.swing.JSlider jStemperaturaArea3;
    private javax.swing.JSlider jTlixo1;
    private javax.swing.JSlider jTlixo2;
    private javax.swing.JSlider jTlixo3;
    // End of variables declaration//GEN-END:variables
}
